name = "real_time_chat"
version = "1.0.0"

[dependencies]
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
mist = ">= 5.0.3 and < 6.0.0"
gleam_stdlib = ">= 0.67.1 and < 1.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"

[dev-dependencies]
gleescript = ">= 1.4.0 and < 2.0.0"
